# Generated by Django 4.2.4 on 2023-09-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ecertificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ecertificate',
        ),
    ]
