# Generated by Django 4.2.4 on 2023-09-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_ecertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='file',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='name',
        ),
    ]
