# Generated by Django 4.2.4 on 2023-09-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_certificate_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', upload_to='uploads/')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='certificate',
            name='event_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='certificate',
            name='summary_event',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='reg_no',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.organization'),
            preserve_default=False,
        ),
    ]
